using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using static PKHeX.Core.AutoMod.APILegality;
using PKHeX.Core;

namespace PKHeX.Core.AutoMod;

/// <summary>
/// Contains logic to create a <see cref="PKM"/> from its elemental details.
/// </summary>
public static class Legalizer
{
    public static bool EnableEasterEggs { get; set; } = true;

    /// <summary>
    /// Tries to regenerate the <see cref="pk"/> into a valid pkm.
    /// </summary>
    /// <param name="pk">Currently invalid pkm data</param>
    /// <returns>Legalized PKM (hopefully legal)</returns>
    public static PKM Legalize(this PKM pk)
    {
        var tr = TrainerSettings.GetSavedTrainerData(pk.Format);
        return tr.MutateLanguage((LanguageID)pk.Language, pk.Version).Legalize(pk);
    }

    /// <summary>
    /// Tries to regenerate the <see cref="pk"/> into a valid pkm.
    /// </summary>
    /// <param name="tr">Source/Destination trainer</param>
    /// <param name="pk">Currently invalid pkm data</param>
    /// <returns>Legalized PKM (hopefully legal)</returns>
    public static PKM Legalize(this ITrainerInfo tr, PKM pk, LegalityAnalysis? la = null)
    {
        var set = new ShowdownSet(pk); //Regen Template may carry illegal traits, Use basic Showdown set to revert to a legal template.
        var almres = tr.GetLegalFromSet(set, pk, la?.EncounterOriginal); //keep the current pkm as template
        var result = almres.Status;
        
        // If legalization failed, try again with the Pokemon's original generation
        if (result == LegalizationResult.Failed)
        {
            var originalGen = GetOriginalGeneration(pk.Species);
            if (originalGen != tr.Generation)
            {
                var originalTr = TrainerSettings.GetSavedTrainerData(originalGen);
                var retrySet = new ShowdownSet(pk);
                var retryRes = originalTr.GetLegalFromSet(retrySet, pk, la?.EncounterOriginal);
                if (retryRes.Status == LegalizationResult.Regenerated)
                {
                    return retryRes.Created;
                }
            }
        }
        
        return result == LegalizationResult.VersionMismatch ? throw new MissingMethodException("PKHeX and Plugins have a version mismatch") : almres.Created;
    }

    /// <summary>
    /// Tries to regenerate the <see cref="pk"/> into a valid pkm. For Blazor WASM.
    /// </summary>
    /// <param name="tr">Source/Destination trainer</param>
    /// <param name="pk">Currently invalid pkm data</param>
    /// Will timeout after the configured at <see cref="APILegality.Timeout"/>
    /// <returns>Legalized PKM (hopefully legal)</returns>
    public static async Task<PKM> LegalizeAsync(this ITrainerInfo tr, PKM pk)
    {
        var set = new ShowdownSet(pk);
        var almres = await tr.GetLegalFromSetAsync(set);
        var result = almres.Status;
        return result == LegalizationResult.VersionMismatch ? throw new MissingMethodException("PKHeX and Plugins have a version mismatch") : almres.Created;
    }

    /// <summary>
    /// Imports <see cref="sets"/> to a provided <see cref="arr"/>, with a context of <see cref="tr"/>.
    /// </summary>
    /// <param name="tr">Source/Destination trainer</param>
    /// <param name="sets">Set data to import</param>
    /// <param name="arr">Current list of data to write to</param>
    /// <param name="invalidAPISets">Returned list of invalid sets that failed to be generated by this api call</param>
    /// <param name="timedoutSets">Returned list of sets that failed to be generated in the premitted time.</param>
    /// <param name="start">Starting offset to place converted details</param>
    /// <param name="overwrite">Overwrite</param>
    /// <returns>Result code indicating success or failure</returns>
    public static AutoModErrorCode ImportToExisting(this SaveFile tr, IReadOnlyList<ShowdownSet> sets, IList<PKM> arr, out List<RegenTemplate> invalidAPISets, out List<RegenTemplate> timedoutSets, int start = 0, bool overwrite = true)
    {
        var emptySlots = overwrite ? Enumerable.Range(start, sets.Count).Where(set => set < arr.Count).ToList() : FindAllEmptySlots(arr, start);
        invalidAPISets = [];
        timedoutSets = [];

        if (emptySlots.Count < sets.Count)
            return AutoModErrorCode.NotEnoughSpace;

        var generated = 0;
        for (int i = 0; i < sets.Count; i++)
        {
            var set = sets[i];
            var regen = new RegenTemplate(set, tr.Generation);
            if (set.InvalidLines.Count > 0)
                return AutoModErrorCode.InvalidLines;

            Debug.WriteLine($"Generating Set: {GameInfo.Strings.Species[set.Species]}");
            var almres = tr.GetLegalFromSet(regen);
            if (almres.Status == LegalizationResult.VersionMismatch)
                return AutoModErrorCode.VersionMismatch;

            var pk = almres.Created;
            pk.ResetPartyStats();
            pk.SetBoxForm();
            if (almres.Status == LegalizationResult.Failed)
                invalidAPISets.Add(regen);

            if (almres.Status == LegalizationResult.Timeout)
                timedoutSets.Add(regen);

            var index = emptySlots[i];
            tr.SetBoxSlotAtIndex(pk, index);
            generated++;
        }

        foreach (var r in timedoutSets)
            Dump(r);

        foreach (var r in invalidAPISets)
            Dump(r, true);

        Debug.WriteLine($"API Generated Sets: {generated - invalidAPISets.Count - timedoutSets.Count}/{sets.Count}, {invalidAPISets.Count} were invalid and {timedoutSets.Count} timed out.");
        foreach (var set in invalidAPISets)
            Debug.WriteLine(set.Text);

        return AutoModErrorCode.None;
    }

    public static void Dump(RegenTemplate set, bool invalid = false)
    {
        var msg = (invalid ? $"[Invalid] [DateTime: {DateTime.Now}]" : $"[Timeout : {Timeout} seconds] [DateTime: {DateTime.Now}]") + Environment.NewLine + set.Text + Environment.NewLine;
        System.IO.File.AppendAllText("error_log.txt", msg);
    }

    /// <summary>
    /// Imports a <see cref="set"/> to create a new <see cref="PKM"/> with a context of <see cref="tr"/>.
    /// </summary>
    /// <param name="tr">Source/Destination trainer</param>
    /// <param name="set">Set data to import</param>
    /// <returns>Legalization Result (hopefully legal)</returns>
    public static AsyncLegalizationResult GetLegalFromSet(this ITrainerInfo tr, IBattleTemplate set)
    {
        var template = EntityBlank.GetBlank(tr);
        if (template.Version == 0)
            template.Version = tr.Version;

        EncounterMovesetGenerator.OptimizeCriteria(template, tr);
        template.ApplySetDetails(set);
        return tr.GetLegalFromSet(set, template);
    }
    /// <summary>
    /// For Blazor WASM
    /// </summary>
    /// <param name="tr"></param>
    /// <param name="set"></param>
    /// <returns></returns>
    public static async Task<AsyncLegalizationResult> GetLegalFromSetAsync(this ITrainerInfo tr, IBattleTemplate set)
    {
        AsyncLegalizationResult GetLegal()
        {
            var template = EntityBlank.GetBlank(tr);
            if (template.Version == 0)
                template.Version = tr.Version;

            EncounterMovesetGenerator.OptimizeCriteria(template, tr);
            template.ApplySetDetails(set);
            return tr.GetLegalFromSet(set, template);
        }
        return await Task.Run(GetLegal);
    }
    /// <summary>
    /// Regenerates the set by searching for an encounter that can generate the template.
    /// </summary>
    /// <param name="tr">Trainer Data that was passed in</param>
    /// <param name="set">Showdown set being used</param>
    /// <param name="template">template PKM to legalize</param>
    /// <returns>Legalization Result</returns>
    private static AsyncLegalizationResult GetLegalFromSet(this ITrainerInfo tr, IBattleTemplate set, PKM template, IEncounterable? enc = null)
    {
        if (set is ShowdownSet s)
            set = new RegenTemplate(s, tr.Generation);

        var almres = tr.TryAPIConvert(set, template,enc: enc);
        if (almres.Status == LegalizationResult.Regenerated)
            return almres;

        if (EnableEasterEggs)
        {
            var easteregg = tr.GetEasterEggFromSet(set, template);
            return almres with { Created = easteregg };
        }

        return almres;
    }

    private static PKM GetEasterEggFromSet(this ITrainerInfo tr, IBattleTemplate set, PKM template)
    {
        var species = (ushort)EasterEggs.GetMemeSpecies(template.Context);

        template.Species = species;
        var form = template.GetAvailableForm();
        if (form is not { } f)
            return template;

        template.Form = f;
        var legalencs = tr.GetRandomEncounter(species, f, set.Shiny, false, false, out var legal);
        if (legalencs && legal != null)
            template = legal;

        template.SetNickname(EasterEggs.GetMemeNickname(template.Context));
        return template;
    }

    private static byte? GetAvailableForm(this PKM pk)
    {
        var species = pk.Species;
        var pi = pk.PersonalInfo;
        var formcount = pi.FormCount;
        if (formcount == 0)
            return null;

        if (!(pk.SWSH || pk.BDSP || pk.LA))
            return pk.Form;

        static bool IsPresentInGameSWSH(ushort species, byte form) => PersonalTable.SWSH.IsPresentInGame(species, form);
        static bool IsPresentInGameBDSP(ushort species, byte form) => PersonalTable.BDSP.IsPresentInGame(species, form);
        static bool IsPresentInGameLA(ushort species, byte form) => PersonalTable.LA.IsPresentInGame(species, form);
        for (byte f = 0; f < formcount; f++)
        {
            if (pk.LA && IsPresentInGameLA(species, f))
                return f;

            if (pk.BDSP && IsPresentInGameBDSP(species, f))
                return f;

            if (pk.SWSH && IsPresentInGameSWSH(species, f))
                return f;
        }
        return null;
    }

    /// <summary>
    /// API Legality
    /// </summary>
    /// <param name="tr">trainer data</param>
    /// <param name="set">showdown set to legalize from</param>
    /// <param name="template">pkm file to legalize</param>
    /// <param name="nativeOnly"></param>
    /// <returns>LegalizationResult</returns>
    public static AsyncLegalizationResult TryAPIConvert(this ITrainerInfo tr, IBattleTemplate set, PKM template, bool nativeOnly = false, IEncounterable? enc = null)
    {
        // Store original values to preserve
        var originalNickname = template.Nickname;
        var originalBall = template.Ball;
        var originalMetDate = template.MetDate;
        var isNicknamed = template.IsNicknamed;
        var originalFriendship = template.CurrentFriendship;
        var originalForm = template.Form;
        var originalSpecies = template.Species;
        
        // Store original trainer data
        var originalOT = template.OriginalTrainerName;
        var originalTID16 = template.TID16;
        var originalSID16 = template.SID16;
        var originalOTGender = template.OriginalTrainerGender;
        
        // Additional encounter data
        var originalMetLocation = template.MetLocation;
        var originalEggLocation = template.EggLocation;
        var originalMetLevel = template.MetLevel;
        var originalCharacteristic = template.Characteristic;
        
        // Store original moves
        var originalMoves = new ushort[4];
        template.GetMoves(originalMoves);

        var almres = tr.GetLegalFromTemplateTimeout(template, set, nativeOnly, enc: enc);
        if (almres.Status != LegalizationResult.Regenerated)
            return almres;

        var pkm = almres.Created;
        
        // Get the legality analysis for the original and new PKM
        var originalLA = new LegalityAnalysis(template);
        var newLA = new LegalityAnalysis(pkm);
        
        // Get encounter info
        var originalEncounter = originalLA.EncounterOriginal;
        var newEncounter = newLA.EncounterOriginal;
        
        // Only preserve original data if the original Pokémon was legal
        // or if we're using the same encounter type
        bool originalWasLegal = originalLA.Valid;
        bool sameEncounterType = originalEncounter?.GetType() == newEncounter?.GetType();
        bool canPreserveMetData = originalWasLegal || sameEncounterType;
        
        // Determine if this is a legendary, mythical, or other special Pokémon
        bool isSpecialPokemon = EntityInfo.IsSpecialEncounter(pkm.Species);
        bool canHatchFromEgg = !EntityInfo.IsEggIncompatible(pkm.Species, pkm.Form, tr.Generation);
        
        // Special handling for legendaries, mythicals, and special encounters
        if (isSpecialPokemon)
        {
            // For special Pokémon, only preserve metadata if the original was legal
            // or if it's the same encounter type
            if (canPreserveMetData)
            {
                // We can preserve the met data
                pkm.MetLocation = originalMetLocation;
                pkm.MetLevel = originalMetLevel;
                
                // Only preserve ball if it would be legal
                var tempBall = pkm.Clone();
                tempBall.Ball = originalBall;
                var ballLA = new LegalityAnalysis(tempBall);
                if (ballLA.Valid)
                    pkm.Ball = originalBall;
            }
        }
        else if (!canHatchFromEgg && originalEggLocation == 0)
        {
            // For non-egg-compatible Pokémon that weren't from eggs
            if (canPreserveMetData)
            {
                pkm.MetLocation = originalMetLocation;
                pkm.MetLevel = originalMetLevel;
                pkm.Ball = originalBall;
            }
        }
        else
        {
            // For regular Pokémon
            pkm.MetDate = originalMetDate;
            
            // Check if original ball is legal
            var tempBall = pkm.Clone();
            tempBall.Ball = originalBall;
            var ballLA = new LegalityAnalysis(tempBall);
            if (ballLA.Valid)
                pkm.Ball = originalBall;
        }

        // Additional ball preservation for static encounters
        if (newEncounter?.GetType().Name.StartsWith("EncounterStatic") == true && originalBall != 0)
        {
            var tempBall = pkm.Clone();
            tempBall.Ball = originalBall;
            var ballLA = new LegalityAnalysis(tempBall);
            if (ballLA.Valid)
                pkm.Ball = originalBall;
        }
        
        // Restore original values that don't affect legality
        if (isNicknamed)
        {
            pkm.Nickname = originalNickname;
            pkm.IsNicknamed = true;
        }
        
        pkm.CurrentFriendship = originalFriendship;
        
        // Only restore form if the species hasn't changed and it's not a form that affects legality
        if (pkm.Species == originalSpecies)
        {
            var pi = pkm.PersonalInfo;
            bool isFormChangeable = pi.HasForms || pkm.Species is (int)Species.Silvally or (int)Species.Arceus;
            bool isBattleOnlyForm = FormInfo.IsBattleOnlyForm(pkm.Species, originalForm, pkm.Format);
            
            if (isFormChangeable && !isBattleOnlyForm)
            {
                // Check if the original form would be legal
                var tempPkm = pkm.Clone();
                tempPkm.Form = originalForm;
                var formLegalityAnalysis = new LegalityAnalysis(tempPkm);
                
                // Only restore original form if it would be legal
                if (formLegalityAnalysis.Valid)
                    pkm.Form = originalForm;
            }
        }
        
        // Restore original trainer data
        pkm.OriginalTrainerName = originalOT;
        pkm.TID16 = originalTID16;
        pkm.SID16 = originalSID16;
        pkm.OriginalTrainerGender = originalOTGender;
        
        // Handle moves - try to preserve original moves if they're legal
        var legalMoveSet = new MoveSet(pkm);
        var originalMoveSet = new MoveSet(template);

        // Verify each original move and use it if it's legal in the new Pokémon
        for (int i = 0; i < 4; i++)
        {
            if (originalMoveSet.Moves[i] == 0) // Skip empty moves
                continue;
                
            // Create a test Pokémon with the move we want to verify
            var testPkm = pkm.Clone();
            testPkm.SetMove(i, originalMoveSet.Moves[i]);
            var legality = new LegalityAnalysis(testPkm);
            
            // Check if the move info for this slot is valid
            if (legality.Info.Moves[i].Valid)
            {
                // Move is valid, so use it
                legalMoveSet.Moves[i] = originalMoveSet.Moves[i];
                
                // Also copy the PP if possible
                legalMoveSet.Moves_PP[i] = Math.Min(
                    originalMoveSet.Moves_PP[i], 
                    testPkm.GetMovePP(originalMoveSet.Moves[i], 0)
                );
            }
        }
        
        // Apply the legal moves to the Pokémon
        legalMoveSet.ApplyTo(pkm);
        
        // Set trainer data after everything else
        var trainer = TrainerSettings.GetSavedTrainerData(pkm, tr);
        pkm.SetAllTrainerData(trainer);
        
        // Make sure the result is still legal
        var finalLA = new LegalityAnalysis(pkm);
        
        // If our modifications made the Pokémon illegal, revert to the original legalized version
        if (!finalLA.Valid)
        {
            return almres;
        }
        
        return new AsyncLegalizationResult(pkm, almres.Status);
    }

    /// <summary>
    /// Helper class to manage move sets easily
    /// </summary>
    private class MoveSet
    {
        public readonly ushort[] Moves = new ushort[4];
        public readonly int[] Moves_PP = new int[4];
        
        public MoveSet(PKM pkm)
        {
            Moves[0] = pkm.Move1;
            Moves[1] = pkm.Move2;
            Moves[2] = pkm.Move3;
            Moves[3] = pkm.Move4;
            
            Moves_PP[0] = pkm.Move1_PP;
            Moves_PP[1] = pkm.Move2_PP;
            Moves_PP[2] = pkm.Move3_PP;
            Moves_PP[3] = pkm.Move4_PP;
        }
        
        public void ApplyTo(PKM pkm)
        {
            pkm.Move1 = Moves[0];
            pkm.Move2 = Moves[1];
            pkm.Move3 = Moves[2];
            pkm.Move4 = Moves[3];
            
            pkm.Move1_PP = (byte)Moves_PP[0];
            pkm.Move2_PP = (byte)Moves_PP[1];
            pkm.Move3_PP = (byte)Moves_PP[2];
            pkm.Move4_PP = (byte)Moves_PP[3];
        }
    }

    /// <summary>
    /// Helper class with utility methods for entity information
    /// </summary>
    private static class EntityInfo
    {
        /// <summary>
        /// Checks if a species is considered a special encounter (legendary, mythical, etc.)
        /// </summary>
        public static bool IsSpecialEncounter(ushort species)
        {
            return IsLegendary(species) || IsMythical(species) || IsSubLegendary(species);
        }
        
        /// <summary>
        /// Checks if a species is a legendary Pokémon
        /// </summary>
        public static bool IsLegendary(ushort species) => species switch
        {
            144 or 145 or 146 or 150 or // Kanto
            249 or 250 or // Johto
            377 or 378 or 379 or 380 or 381 or 382 or 383 or 384 or // Hoenn
            480 or 481 or 482 or 483 or 484 or 485 or 486 or 487 or 488 or // Sinnoh
            638 or 639 or 640 or 641 or 642 or 643 or 644 or 646 or // Unova
            716 or 717 or 718 or // Kalos
            785 or 786 or 787 or 788 or 789 or 790 or 791 or 792 or 800 or // Alola
            888 or 889 or 890 or 891 or 892 or 894 or 895 or 896 or 897 or 898 or // Galar
            905 or 1001 or 1002 or 1003 or 1007 or 1008 => true, // Paldea
            _ => false
        };
        
        /// <summary>
        /// Checks if a species is a mythical Pokémon
        /// </summary>
        public static bool IsMythical(ushort species) => species switch
        {
            151 or // Mew
            251 or // Celebi
            385 or // Jirachi
            386 or // Deoxys
            489 or 490 or 491 or 492 or 493 or // Sinnoh
            494 or 647 or 648 or 649 or // Unova
            719 or 720 or 721 or // Kalos
            801 or 802 or // Alola
            807 or 808 or 809 or // Let's Go
            893 => true, // Galar
            _ => false
        };
        
        /// <summary>
        /// Checks if a species is a sub-legendary Pokémon
        /// </summary>
        public static bool IsSubLegendary(ushort species) => species switch
        {
            // These are typically static encounters
            // We'll consider Ultra Beasts and Kubfu/Urshifu as "sub-legendaries" as well
            > 772 and < 800 or // Ultra Beasts
            > 144 and < 146 or // Birds
            > 243 and < 246 or // Beasts
            > 375 and < 378 or // Regis
            > 480 and < 487 or // Musketeers, Lati@s, etc
            > 637 and < 641 or // Swords of Justice
            > 784 and < 788 or // Tapus
            > 104 and < 115 or // Various others
            > 903 and < 1000 => true, // Gen 9+
            _ => false
        };
        
        /// <summary>
        /// Checks if a species is incompatible with being hatched from an egg
        /// </summary>
        public static bool IsEggIncompatible(ushort species, byte form, int generation)
        {
            // Legendaries, mythicals, and most form-specific Pokémon can't breed
            if (IsLegendary(species) || IsMythical(species) || IsSubLegendary(species))
                return true;
                
            if (species is 132 or 774) // Ditto or Minior
                return true;
                
            // Form edge cases that can't breed
            return form > 0 && species is 201 or 421 or 422 or 423 or 550 or 555 or 585 or 586 or 641 or 642 or 645 or 647 or 648 or 649 or 670 or 671 or 710 or 711 or 741 or 745 or 746 or 747 or 748 or 773 or 774 or 778 or 849 or 854 or 855 or 875 or 876 or 877 or 888 or 889 or 892;
        }
    }

    /// <summary>
    /// Method to find all empty slots in a current box
    /// </summary>
    /// <param name="data">Box Data of the save file</param>
    /// <param name="start">Starting position for finding an empty slot</param>
    /// <returns>A list of all indices in the current box that are empty</returns>
    public static List<int> FindAllEmptySlots(IList<PKM> data, int start)
    {
        var emptySlots = new List<int>();
        for (int i = start; i < data.Count; i++)
        {
            if (data[i].Species == 0)
                emptySlots.Add(i);
        }
        return emptySlots;
    }

    /// <summary>
    /// Gets the original generation a Pokemon was introduced in
    /// </summary>
    private static byte GetOriginalGeneration(ushort species)
    {
        return species switch
        {
            <= 151 => 1,  // Kanto
            <= 251 => 2,  // Johto
            <= 386 => 3,  // Hoenn
            <= 493 => 4,  // Sinnoh
            <= 649 => 5,  // Unova
            <= 721 => 6,  // Kalos
            <= 807 => 7,  // Alola
            <= 898 => 8,  // Galar
            _ => 9,       // Paldea
        };
    }
}
